apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../jbosseap-base
- resources/secret.yaml

namePrefix: sample-a-

commonLabels:
  application: sample-a

images:
- name: application-image
  newName: abkura/jboss-profiler
  newTag: latest

patches:
- path: patches/env-patch.yaml
  target:
    kind: Deployment
      
- path: resources/volumes.yaml
  target:
    kind: Deployment
    
- path: resources/resource-limits.yaml
  target:
    kind: Deployment
